// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT

  STARTUP

  LOAD_CONTACTS
  LOAD_CONTACTS_SUCCESS
  LOAD_CONTACTS_FAILURE

  TEMPERATURE_REQUEST
  TEMPERATURE_RECEIVE
  TEMPERATURE_FAILURE


  COUNTRY_SELECTED
  PHONE_NUMBER_CREATE
  PHONE_NUMBER_CREATE_STARTED
  PHONE_NUMBER_CREATE_SUCCESS
  PHONE_NUMBER_CREATE_FAILURE

  PHONE_NUMBER_UPDATING
  PHONE_NUMBER_UPDATE_SUCCESS
  PHONE_NUMBER_UPDATE_FAILURE

  ACCESS_CODE_VERIFIED
  USER_CREATE
  USER_CREATE_STARTED
  USER_CREATE_SUCCESS
  USER_CREATE_FAILURE

  USER_DELETE
  USER_DELETE_SUCCESS
  USER_DELETE_FAILURE

  SEND_PUSH_TO_USER
  SEND_PUSH_TO_USER_SUCCESS
  SEND_PUSH_TO_USER_FAILURE

  CREATE_INSTALLATION
  CREATE_INSTALLATION_SUCCESS
  CREATE_INSTALLATION_FAILURE

  RESET_PASSWORD
  RESET_PASSWORD_SUCCESS
  RESET_PASSWORD_FAILURE

  UPDATE_PASSWORD
  UPDATE_PASSWORD_SUCCESS
  UPDATE_PASSWORD_FAILURE

  UPDATE_PROFILE
  UPDATE_PROFILE_SUCCESS
  UPDATE_PROFILE_FAILURE

  CREATE_ADDRESS
  CREATE_ADDRESS_FAILURE
  CREATE_ADDRESS_SUCCESS

  DELETE_ADDRESS
  DELETE_ADDRESS_FAILURE
  DELETE_ADDRESS_SUCCESS

  FETCH_ADDRESSES
  FETCH_ADDRESSES_FAILURE
  FETCH_ADDRESSES_SUCCESS

  SAVE_ADDRESS
  SAVE_ADDRESS_SUCCESS
  SAVE_ADDRESS_FAILURE

  FETCH_CONFIG
  FETCH_CONFIG_FAILURE
  FETCH_CONFIG_SUCCESS

  FETCH_MONITORS
  FETCH_MONITORS_FAILURE
  FETCH_MONITORS_SUCCESS

  FETCH_DEVICES
  FETCH_DEVICES_FAILURE
  FETCH_DEVICES_SUCCESS

  FETCH_DEVICE_ACTIVITY
  FETCH_DEVICE_ACTIVITY_FAILURE
  FETCH_DEVICE_ACTIVITY_SUCCESS

  RESET_DEVICE_ACTIVITY

  FETCH_DEVICE_CLIMATE
  FETCH_DEVICE_CLIMATE_FAILURE
  FETCH_DEVICE_CLIMATE_SUCCESS

  RESET_DEVICE_CLIMATE

  DEVICE_CREATE
  DEVICE_CREATE_STARTED
  DEVICE_CREATE_SUCCESS
  DEVICE_CREATE_FAILURE
  DEVICE_GET
  DEVICE_GET_SUCCESS
  DEVICE_GET_FAILURE
  DEVICE_UPDATE
  DEVICE_UPDATE_SUCCESS
  DEVICE_UPDATE_FAILURE
  DEVICE_DELETE
  DEVICE_DELETE_SUCCESS
  DEVICE_DELETE_FAILURE

  SNOOZE_DEVICE
  SNOOZE_DEVICE_SUCCESS
  SNOOZE_DEVICE_FAILURE

  DEVICE_ADDRESS_SELECT
  DEVICE_TYPE_SELECT
  PROV_MECH_SELECT
  DEVICE_LOCATION_SELECT
  DEVICE_NAME_SELECT
  WIFI_INFO_ENTER
  PROVISION_STEP_CHANGE
  TIMER
  COUNTDOWN_UPDATE
  POLL_DEVICE_STATUS
  RESET_STEP
  PROVISION_STATE_RESET
  PROVISIONING_ERROR_RESET
  PROVISION_CANCEL
  PROVISION_CANCEL_CLEANUP
  PROVISION_ATTEMPT_COMPLETE
  DEVICE_LAT_LONG

  GET_ALARM_MODELS
  GET_ALARM_MODELS_SUCCESS
  GET_ALARM_MODELS_FAILURE

  CREATE_MONITOR
  CREATE_MONITOR_SUCCESS
  CREATE_MONITOR_FAILURE

  CREATE_PROMOTION
  CREATE_PROMOTION_SUCCESS
  CREATE_PROMOTION_FAILURE

  DELETE_MONITOR
  DELETE_MONITOR_SUCCESS
  DELETE_MONITOR_FAILURE

  UPDATE_INVITATION
  UPDATE_INVITATION_SUCCESS
  UPDATE_INVITATION_FAILURE

  FINISH_NOTIFICATION_ALARM
  PLAY_NOTIFICATION_ALARM
  STOP_NOTIFICATION_ALARM
  END_NOTIFICATION_ALARM
`)
