// leave off @2x/@3x
const images = {
  appIconAbout: require('../Images/app-icon-about.png'),
  address: require('../Images/address-icon.png'),
  addressSmall: require('../Images/address-small.png'),
  information: require('../Images/information.png'),
  help: require('../Images/help.png'),
  monitor: require('../Images/monitor.png'),
  monitorSmall: require('../Images/monitor-small.png'),
  person: require('../Images/person.png'),
  logo: require('../Images/roost_logo.png'),
  hamburger: require('../Images/hamburger.png'),
  home: require('../Images/home_icon.png'),
  homeIcon: require('../Images/home.png'),
  exit: require('../Images/exit.png'),
  arrowBack: require('../Images/arrow-back.png'),
  arrowForward: require('../Images/arrow-forward.png'),
  key: require('../Images/key.png'),
  trash: require('../Images/trash.png'),
  empty: require('../Images/empty.png'),

  bedroom: require('../Images/bed-circle.png'),
  masterBedroom: require('../Images/large-bed-circle.png'),
  bathroom: require('../Images/shower-circle.png'),
  hallway: require('../Images/hallway-circle.png'),
  hallwayUpstairs: require('../Images/hallway-upstairs-circle.png'),
  kitchen: require('../Images/place-setting-circle.png'),
  basement: require('../Images/basement-circle.png'),
  garage: require('../Images/car-circle.png'),
  closet: require('../Images/hanger-circle.png'),
  customLocation: require('../Images/alarm-seal-circle.png'),
  refrigerator: require('../Images/refrigerator-circle.png'),
  dishwasher: require('../Images/dishwasher-circle.png'),
  sink: require('../Images/sink-circle.png'),
  toilet: require('../Images/toilet-circle.png'),
  wine: require('../Images/wine-circle.png'),
  battery: require('../Images/battery.png'),
  customBattery: require('../Images/custom-battery.png'),
  leakDetector: require('../Images/leak-detector.png'),
  customLeakDetector: require('../Images/custom-leak-detector.png'),
  washingMachine: require('../Images/washing-machine.png'),
  waterHeater: require('../Images/water-heater.png'),
  sumpPump: require('../Images/sump-pump.png'),
  plusSignWhiteCircled: require('../Images/plus-sign-white-circled.png'),
  location: require('../Images/location-icon.png'),
  checkmarkFilled: require('../Images/checkmark-filled.png'),
  tryAgain: require('../Images/icon-try-again.png'),
  smokeAlarmOne: require('../Images/instructions-one.png'),
  smokeAlarmTwo: require('../Images/instructions-two.png'),
  smokeAlarmThree: require('../Images/instructions-three.png'),
  smokeAlarmFour: require('../Images/instructions-four.png'),
  smokeAlarmFive: require('../Images/instructions-five.png'),
  smokeAlarmProvision: require('../Images/provision.png'),
  arrowDown: require('../Images/arrow_down.png'),
  alarmInfo: require('../Images/alarmInfo.png'),
  waterDetectorOne: require('../Images/water-detector-one.jpg'),
  waterDetectorTwo: require('../Images/water-detector-two.jpg'),

  batterySmall: require('../Images/battery-small.png'),
  iconAlert: require('../Images/icon-alert.png'),
  iconWaterAlert: require('../Images/icon-water-alert.png'),
  iconBatteryCritical: require('../Images/icon-battery-critical.png'),
  iconBatteryLow: require('../Images/icon-battery-low.png'),
  iconLate: require('../Images/icon-late.png'),
  iconOk: require('../Images/icon-ok.png'),
  iconSetupIncomplete: require('../Images/icon-setup-incomplete.png'),
  iconSnooze: require('../Images/icon-snooze.png'),
  iconVeryLate: require('../Images/icon-very-late.png'),
  leakDetectorUpright: require('../Images/leak-detector-upright.png'),
  leakDetectorUprightWhite: require('../Images/leak-detector-upright-white.png'),
  movingPerson: require('../Images/moving-person.png'),
  plus: require('../Images/plus-add-icon.png'),
  water: require('../Images/water.png'),

  batteryEmpty: require('../Images/battery-empty.png'),
  batteryFull: require('../Images/battery-full.png'),
  batteryHalf: require('../Images/battery-half.png'),
  wifiEmpty: require('../Images/wifi-empty.png'),
  wifiFull: require('../Images/wifi-full.png'),
  wifiHalf: require('../Images/wifi-half.png'),

  checkboxFilled: require('../Images/checkbox-marked.png'),
  checkboxEmpty: require('../Images/checkbox-blank-outline.png'),

  profile: require('../Images/profile-icon.png'),

  poseidonOne: require('../Images/poseidon-one.jpg'),
  poseidonTwo: require('../Images/poseidon-two.jpg'),
  poseidonThree: require('../Images/poseidon-three.jpg'),
  poseidonFour: require('../Images/poseidon-four.jpg'),

  forkScreen: require('../Images/fork-screen.png'),
  foamOne: require('../Images/foam-one.png'),
  foamTwo: require('../Images/foam-two.png'),

}

export default images
